[2024-04-16T01:19:24.670+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T01:19:24.702+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Tutorial_MALUCO.nvalido manual__2024-04-16T01:19:21.509854+00:00 [queued]>
[2024-04-16T01:19:24.711+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Tutorial_MALUCO.nvalido manual__2024-04-16T01:19:21.509854+00:00 [queued]>
[2024-04-16T01:19:24.803+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T01:19:24.828+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): nvalido> on 2024-04-16 01:19:21.509854+00:00
[2024-04-16T01:19:24.838+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=741) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T01:19:24.848+0000] {standard_task_runner.py:63} INFO - Started process 748 to run task
[2024-04-16T01:19:24.852+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Tutorial_MALUCO', 'nvalido', 'manual__2024-04-16T01:19:21.509854+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpkuinzxj4']
[2024-04-16T01:19:24.854+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask nvalido
[2024-04-16T01:19:25.073+0000] {task_command.py:426} INFO - Running <TaskInstance: Tutorial_MALUCO.nvalido manual__2024-04-16T01:19:21.509854+00:00 [running]> on host df00be3806a2
[2024-04-16T01:19:25.326+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Tutorial_MALUCO' AIRFLOW_CTX_TASK_ID='nvalido' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T01:19:21.509854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T01:19:21.509854+00:00'
[2024-04-16T01:19:25.328+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T01:19:25.329+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-16T01:19:25.330+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo qualidade OK']
[2024-04-16T01:19:25.348+0000] {subprocess.py:86} INFO - Output:
[2024-04-16T01:19:25.351+0000] {subprocess.py:93} INFO - qualidade OK
[2024-04-16T01:19:25.352+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-16T01:19:25.353+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T01:19:25.414+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Tutorial_MALUCO, task_id=nvalido, execution_date=20240416T011921, start_date=20240416T011924, end_date=20240416T011925
[2024-04-16T01:19:25.464+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T01:19:25.486+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T01:19:25.491+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
