[2024-04-17T01:40:13.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T01:40:13.722+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [queued]>
[2024-04-17T01:40:13.734+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [queued]>
[2024-04-17T01:40:13.769+0000] {taskinstance.py:2303} INFO - Starting attempt 16 of 16
[2024-04-17T01:40:13.792+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): captura> on 2024-04-16 22:30:00+00:00
[2024-04-17T01:40:13.802+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1118) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T01:40:13.805+0000] {standard_task_runner.py:63} INFO - Started process 1120 to run task
[2024-04-17T01:40:13.808+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Tutorial_MALUCO', 'captura', 'scheduled__2024-04-16T22:30:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmp39_ludhp']
[2024-04-17T01:40:13.811+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask captura
[2024-04-17T01:40:13.998+0000] {task_command.py:426} INFO - Running <TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [running]> on host 8dbfbc3d620a
[2024-04-17T01:40:14.235+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Tutorial_MALUCO' AIRFLOW_CTX_TASK_ID='captura' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='16' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T22:30:00+00:00'
[2024-04-17T01:40:14.238+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T01:40:14.403+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T01:40:14.405+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FirstDag.py", line 15, in captura
    print("var type: " + type(response))
          ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "type") to str
[2024-04-17T01:40:14.436+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Tutorial_MALUCO, task_id=captura, execution_date=20240416T223000, start_date=20240417T014013, end_date=20240417T014014
[2024-04-17T01:40:14.486+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task captura (can only concatenate str (not "type") to str; 1120)
[2024-04-17T01:40:14.503+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T01:40:14.539+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T01:40:14.629+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
